version: '2.1'
services:
#  mysql:
#    build:
#      context: ./mysql
#    environment:
#      - "MYSQL_ROOT_PASSWORD=root123"
#    container_name: "test-mysql"
#    hostname: "mysql"
#    ports:
#     - "3306:3306"
#  php:
#    image: php:7.1-apache
#    container_name: "test-php"
#    hostname: "php"
#    ports:
#      - "80:80"
#    volumes:
#     - .:/var/www/html
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.2"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    container_name: "test-elasticsearch"
    hostname: "elasticsearch"
    ports:
     - "9200:9200"
  kibana:
    image: "docker.elastic.co/kibana/kibana:5.6.2"
    container_name: "test-kibana"
    hostname: "kibana"
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch